name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - pandas
    - matplotlib
    - plotly
    - PyGithub
    - sklearn
    - scipy
    - keras
    - tensorflow
